version: '3'

services:
  notebook:
    image: jupyter/datascience-notebook:latest
    ports:
      - 8888:8888
    environment:
      NB_USER: $nb_user
      CHOWN_HOME: yes
      GRANT_SUDO: yes
      password: $password
      #CONDA_DIR: /home/$nb_user/.conda/
    working_dir: /home/$nb_user
    user: root
    volumes:
      - jupyter_user:/home/$nb_user
      - condadata:/opt/conda
volumes:
  jupyter_user: {}
  condadata: {}
  